### ISSUE TITLE
Tying Edges to Vertexes

### ISSUE THREAD

**Issue by mwisnefsky** [DesignEngrLab/MIConvexHull#10]
I'm using the Voronoi portion of this and was wondering if it is possible to generate the data structure so that the TCell knows which of the TEdges it is bounded by.  It seems like I can get out a list of the original points with who it's neighbors are, and a list of all edges on the graph.

**Comment by micampbell** [comment]
Sorry. It's been a long time since you posted this. Did you figure something out? I may have a look at doing this in a month or two.

**Comment by mwisnefsky** [comment]
Not yet.  I've been looking at other implementations on and off but have been having difficulty getting the data structure to come out correct.  I can wait to see if you get around to it while I see what I can do.

**Comment by dsehnal** [comment]
A simple solution might be to simply add a list of ``TEdge`` to ``TCell`` and the iterate over the voronoi edges to add each edge to the list:

```cs
class MyEdge : ....

class MyCell : Cell {
  List<MyEdge> Edges;
}

foreach (var edge in voronoie.Edges) {
  edge.Source.Add(edge);
  edge.Target.Add(edge);
}
```
