### ISSUE TITLE
 MathHelper classes not static

### ISSUE THREAD

**Issue by bklooste** [DesignEngrLab/MIConvexHull#11]
Suggest the mathhelper methods esp VectorBetweenVertices become static it should provide superior inlining,.

**Comment by micampbell** [comment]
I'm sorry but MathHelper is not meant to be part of the API for this library. It is an internal class that is given access to the "Positions" or coordinates of the vertices in advance of its operations. It is intended to be accessed by other methods outside of MIConvexHull. Feel free to copy the logic of any of the internal or private functions of MathHelper for use in your application.
