### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by mc0re** [DesignEngrLab/MIConvexHull#14]
It'd be great to have MIConvexHull NuGet package strong-named (signed).

**Comment by micampbell** [comment]
hmm, I don't know what this means. Can you say more? send links?

**Comment by mc0re** [comment]
The MIConvexHull DLL is currently not signed. Singing it is a simple process, described e.g. here: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name

Unless I am mistaken, I see no problem in creating a private/public key pair specifically for the purpose of this project, and publishing both. As long as they are not reused in other projects, I can't imagine how this can go wrong :-)

**Comment by micampbell** [comment]
thanks, it is now signed.
