### ISSUE TITLE
Missing face in convex hull for 2D rectangle

### ISSUE THREAD

**Issue by pantojasc** [DesignEngrLab/MIConvexHull#18]
Hi.

I have a 2D rectangle for which the convex hull is calculated (which should be equal to the rectangle), but one face is missing and instead one face is duplicated.
The triangulation of the rectangle is correct.
A unit test is attached (it's a C# file, but Github only accepts .txt).
[MIConvexHullTest.txt](https://github.com/DesignEngrLab/MIConvexHull/files/1739627/MIConvexHullTest.txt)
Version: 1.1.17.1019

Thank you for your help and effort :)

**Comment by ericgarza70** [comment]
I am seeing the same problem, meanwhile I will iterate the Points field to build the faces

**Comment by ericgarza70** [comment]
The convex hull faces fail for any shape in 2D, a face is duplicated and one is missing. I just created a pull request with the proposed fix. I did not find any unit tests so I did not add pantojasc's test.

**Comment by pantojasc** [comment]
Looking forward to the fix. Thank you for looking into it.
