### ISSUE TITLE
3D Delaunay input

### ISSUE THREAD

**Issue by FixyFede** [DesignEngrLab/MIConvexHull#22]
I'm trying to implement your delaunay triangulation in my code, but everytime i build it visual studio shows me this error

> The input data is degenerate. It appears to exist in 4 dimensions, but it is a 3 dimensional set (i.e. the point of collinear, coplanar, or co-hyperplanar.)

Here is the code I'm using

```
DefaultVertex[] v = new DefaultVertex[5];

v[0] = new DefaultVertex();
v[0].Position = new double[3] { 5.1, 5.8, 0.0 };
v[1] = new DefaultVertex();
v[1].Position = new double[3] { 7.0, 2.8, 0.0 };
v[2] = new DefaultVertex();
v[2].Position = new double[3] { 4.8, 0.1, 0.0 };
v[3] = new DefaultVertex();
v[3].Position = new double[3] { 1.5, 1.4, 0.0 };
v[4] = new DefaultVertex();
v[4].Position = new double[3] { 1.7, 4.9, 0.0 };

 ITriangulation<DefaultVertex, DefaultTriangulationCell<DefaultVertex>> r = Triangulation.CreateDelaunay(v);
```

**Comment by KyrumX** [comment]
Any fix for this?

**Comment by micampbell** [comment]
The error is correct. All the points are co-planar as they all have the same z-value. Please submit 2D points (without the z-value) instead. The library recognizes that the data is 3D, so is attempting to generate tetrahedra - which would all be degenerate (having zero volume). You likely want triangular information.

((Sorry for the delay in responding.))
