### ISSUE TITLE
ConvexHull points index of original input points

### ISSUE THREAD

**Issue by petrasvestartas** [DesignEngrLab/MIConvexHull#23]
Hi,

Is there any way to know the index of  hull points index regarding input points.

In the image below, on the left you see input points and on the right convex hull as mesh and its vertices.
For sure hull vertices are indexed differently than original points.

But is there any way to know that the hull.Point[4] is the first point of input points?
![asda](https://user-images.githubusercontent.com/18013985/45114089-55357e00-b14c-11e8-917a-0f59ebf8db1b.png)

I generate convex hull like this:

 ```
   var vertices = CreateHullVertices(x);
    ConvexHull<DefaultVertex,DefaultConvexFace<DefaultVertex>> hull = ConvexHull.Create(vertices);


    Mesh mesh = new Mesh();
    var convexHullVertices = hull.Points.ToArray();
    foreach(DefaultVertex pt in hull.Points){
      double[] pos = pt.Position;
      mesh.Vertices.Add(new Point3d(pos[0], pos[1], pos[2]));
    }

    foreach( DefaultConvexFace<DefaultVertex> f in hull.Faces){
      int a = Array.IndexOf(convexHullVertices, f.Vertices[0]);
      int b = Array.IndexOf(convexHullVertices, f.Vertices[1]);
      int c = Array.IndexOf(convexHullVertices, f.Vertices[2]);
      mesh.Faces.AddFace(a, b, c);
    }
```

**Comment by xarthurx** [comment]
> Hi,
> 
> Is there any way to know the index of hull points index regarding input points.
> 
> In the image below, on the left you see input points and on the right convex hull as mesh and its vertices. For sure hull vertices are indexed differently than original points.
> 
> But is there any way to know that the hull.Point[4] is the first point of input points? ![asda](https://user-images.githubusercontent.com/18013985/45114089-55357e00-b14c-11e8-917a-0f59ebf8db1b.png)
> 
> I generate convex hull like this:
> 
> ```
>   var vertices = CreateHullVertices(x);
>    ConvexHull<DefaultVertex,DefaultConvexFace<DefaultVertex>> hull = ConvexHull.Create(vertices);
> 
> 
>    Mesh mesh = new Mesh();
>    var convexHullVertices = hull.Points.ToArray();
>    foreach(DefaultVertex pt in hull.Points){
>      double[] pos = pt.Position;
>      mesh.Vertices.Add(new Point3d(pos[0], pos[1], pos[2]));
>    }
> 
>    foreach( DefaultConvexFace<DefaultVertex> f in hull.Faces){
>      int a = Array.IndexOf(convexHullVertices, f.Vertices[0]);
>      int b = Array.IndexOf(convexHullVertices, f.Vertices[1]);
>      int c = Array.IndexOf(convexHullVertices, f.Vertices[2]);
>      mesh.Faces.AddFace(a, b, c);
>    }
> ```

You can actually easily create a Dictionary and hash it. I don't find a build-in approach for this.

**Comment by petrasvestartas** [comment]
Make sense, just be aware that building round point hash can be slow on large sets. Would be nice if the original algorithm would provide this ...

**Comment by xarthurx** [comment]
> Make sense, just be aware that building round point hash can be slow on large sets. Would be nice if the original algorithm would provide this ...

You can use `float` instead of `double` to do that, or hash with a specific number of digits. 
On my side, million-level points is not a problem.
