### ISSUE TITLE
Signing of nuget package

### ISSUE THREAD

**Issue by Jordan181** [DesignEngrLab/MIConvexHull#29]
Hi, I have noticed that someone previously asked to get the nuget package signed and you had responded saying that it had been done. However, the package you are distributing on nuget.org is still not signed - when I download and try to build it into my signed solution, Visual Studio complains. Please could you look into this?

**Comment by micampbell** [comment]
I believe this is fixed now. Please have a look and let me know.

**Comment by wsjlmq** [comment]
Hi @micampbell    I also encountered the same problem. How can I solve it？
