### ISSUE TITLE
Converting Solution Number 7 to Unity?

### ISSUE THREAD

**Issue by PorkyPine1** [DesignEngrLab/MIConvexHull#4]
Hello all! I know this really isnt a forum, and is actually an issue thingy. I was actually looking for help converting the seventh solution (Delaunay Generation) to Unity, using their Mesh System. Could i possibly get help from the developer itself?

I must either do this or convert the generated Visual Studio Model3DClass to a .fbx / .dae / .obj file.
Any help?

**Comment by micampbell** [comment]
I wouldn't involve the WPF classes if possible (Model3D, etc).
In that example, the key line is in RandomTriangulation.cs, line 62:          
var tetrahedrons = Triangulation.CreateDelaunay<Vertex, Tetrahedron>(vertices).Cells;
You want to make sure you have a class like Vertex and Tetrahedron to pass in and retrieve the correct data. You may need to do a conversion going in and or coming out of that method.
