### ISSUE TITLE
Question: is there any built in function to determine if a point is inside a 3D convex polygon ?

### ISSUE THREAD

**Issue by petersesztak** [DesignEngrLab/MIConvexHull#46]
first of all : thanks for your lib.

Question: is there any built in function to determine if a point is inside a 3D convex polygon ?

Thanks for your kind reply in advance,
Péter

**Comment by massonib** [comment]
No, there is not. This library is strictly for finding the convex hull. Please refer to TVGL's MiscFunctions.cs (https://github.com/DesignEngrLab/TVGL) for functions such as this.
