### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by fcabrera23** [DesignEngrLab/MIConvexHull#8]
Hi, is this library compatible with Net Core 1.0 ? Im trying to install it but got some errors. Thanks

**Comment by micampbell** [comment]
I just pushed changes that include a version for Net Core 1.0. Let me know if it works for you. You should run the new tester project to see how it interfaces.

**Comment by fcabrera23** [comment]
Ok thanks, is the package available via nuget? Excelent work!

**Comment by micampbell** [comment]
Yes, I pushed this to NuGet.
